-- Auto-generated from schema-map-postgres.psd1 (map@db2f8b8)
-- engine: postgres
-- table:  audit_log
CREATE TABLE IF NOT EXISTS audit_log (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  table_name VARCHAR(100) NOT NULL,
  record_id BIGINT NOT NULL,
  changed_by BIGINT NULL,
  change_type TEXT NOT NULL,
  old_value JSONB NULL,
  new_value JSONB NULL,
  changed_at TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  ip_bin BYTEA NULL,
  user_agent VARCHAR(1024) NULL,
  request_id VARCHAR(100) NULL,
  CONSTRAINT chk_audit_change_type CHECK (change_type IN ('INSERT','UPDATE','DELETE'))
);
